FROM openjdk:8-jre-alpine
RUN apk update && apk add bash && apk add curl && apk add libc6-compat && apk add mysql-client
RUN curl --create-dirs -o ~/.embulk/bin/embulk -L "https://dl.embulk.org/embulk-latest.jar" && \
  chmod +x ~/.embulk/bin/embulk && \
  echo 'export PATH="$HOME/.embulk/bin:$PATH"' >> ~/.bashrc && \
  source ~/.bashrc && \
  embulk gem install embulk-output-mysql && embulk gem install embulk-filter-mask
